create table Public."covid_vaccinations"(
iso_code varchar(50),
continent varchar(50),
location varchar(50),
date date,
total_tests	bigint,
new_tests bigint,
total_tests_per_thousand decimal(10,3),
new_tests_per_thousand decimal(10,3),
new_tests_smoothed decimal(11,3),
new_tests_smoothed_per_thousand decimal(10,3),
positive_rate  decimal(10,3),
tests_per_case  decimal(10,3),
tests_units varchar(50),
total_vaccinations bigint,
people_vaccinated bigint,
people_fully_vaccinated bigint,
total_boosters bigint,
new_vaccinations bigint,
new_vaccinations_smoothed decimal(11,3),
total_vaccinations_per_hundred  decimal(10,3),
people_vaccinated_per_hundred  decimal(10,3),
people_fully_vaccinated_per_hundred decimal(10,3),
total_boosters_per_hundred decimal(10,3),
new_vaccinations_smoothed_per_million decimal(10,3),
new_people_vaccinated_smoothed decimal(11,3),
new_people_vaccinated_smoothed_per_hundred decimal(10,3),
stringency_index decimal(10,3),
median_age decimal(10,3),
aged_65_older decimal(10,3),
aged_70_older decimal(10,3),
gdp_per_capita decimal(10,3),
extreme_poverty decimal(10,3),
cardiovasc_death_rate decimal(10,3),
diabetes_prevalence decimal(10,3),
female_smokers  decimal(10,3),
male_smokers decimal(10,3),
handwashing_facilities decimal(10,3),
hospital_beds_per_thousand decimal(10,3),
life_expectancy decimal(10,3),
human_development_index	decimal(10,3),
excess_mortality_cumulative_absolute decimal(10,3),
excess_mortality_cumulative	decimal(10,3), 
excess_mortality decimal(10,3),
excess_mortality_cumulative_per_million decimal(10,3));

select * from Public."covid_vaccinations";

copy public."covid_vaccinations" from 'C:\Users\Jacob\AbisheakJacob\covid_19_deaths\resources\covid_vaccinations.csv' delimiter ',' csv header; 

